'use client'

import { useRef } from 'react'
import { motion, useScroll, useTransform } from 'framer-motion'
import { ArrowUpRight } from 'lucide-react'

const marqueeImages = [
  'https://motionsites.ai/assets/hero-space-voyage-preview-eECLH3Yc.gif', 'https://motionsites.ai/assets/hero-codenest-preview-Cgppc2qV.gif', 'https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif', 'https://motionsites.ai/assets/hero-stellar-ai-v2-preview-DjvxjG3C.gif', 'https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif', 'https://motionsites.ai/assets/hero-transform-data-preview-Cx5OU29N.gif', 'https://motionsites.ai/assets/hero-vitara-preview-Cjz2QYyU.gif', 'https://motionsites.ai/assets/hero-terra-preview-BFjrCr7T.gif', 'https://motionsites.ai/assets/hero-skyelite-preview-DHaZIgUv.gif', 'https://motionsites.ai/assets/hero-aethera-preview-DknSlcTa.gif', 'https://motionsites.ai/assets/hero-designpro-preview-D8c5_een.gif', 'https://motionsites.ai/assets/hero-stellar-ai-preview-D3HL6bw1.gif', 'https://motionsites.ai/assets/hero-xportfolio-preview-D4A8maiC.gif', 'https://motionsites.ai/assets/hero-orbit-web3-preview-BXt4OttD.gif', 'https://motionsites.ai/assets/hero-nexora-preview-cx5HmUgo.gif', 'https://motionsites.ai/assets/hero-evr-ventures-preview-DZxeVFEX.gif', 'https://motionsites.ai/assets/hero-planet-orbit-preview-DWAP8Z1P.gif', 'https://motionsites.ai/assets/hero-new-era-preview-CocuDUm9.gif', 'https://motionsites.ai/assets/hero-wealth-preview-B70idl_u.gif', 'https://motionsites.ai/assets/hero-luminex-preview-CxOP7ce6.gif', 'https://motionsites.ai/assets/hero-celestia-preview-0yO3jXO8.gif',
]

const projects = [
  ['01', 'Client', 'Nextlevel Studio', ['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055344_5eff02e0-87a5-41ce-b64f-eb08da8f33db.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055431_11d841fd-8b41-46a5-82e4-b04f2407a7d8.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055451_e317bf2d-28d4-48cc-86b0-6f72f25b6327.png&w=1280&q=85']],
  ['02', 'Personal', 'Aura Brand Identity', ['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055654_911201c5-36d9-4bc6-bac7-331adfce159f.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055723_5ceda0b8-d9c2-4665-b2e3-83ba19ba76d1.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055753_adc5dcbd-a8e6-49c0-b43a-9b030d835cea.png&w=1280&q=85']],
  ['03', 'Client', 'Solaris Digital', ['https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055759_963cfb0b-4bd1-4b0f-9d0a-09bd6cf95b2f.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_060108_438f781a-9846-4dcc-89ab-c4e6cb830f5b.png&w=1280&q=85', 'https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055818_9d062121-ad7e-46b9-999a-1a6a692ef1ee.png&w=1280&q=85']],
] as const

function ContactButton() { return <a className="contact-pill" href="#contact">Contact Me <ArrowUpRight aria-hidden="true" /></a> }
function FadeIn({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-50px' }} transition={{ duration: .7, delay, ease: [.25, .1, .25, 1] }}>{children}</motion.div> }
function Marquee() { return <section className="marquee-3d">{[marqueeImages.slice(0, 11), marqueeImages.slice(11)].map((row, i) => <div className={i ? 'marquee-track reverse' : 'marquee-track'} key={i}>{[...row, ...row, ...row].map((src, j) => <img key={`${src}-${j}`} src={src} alt="3D project preview" loading="lazy" />)}</div>)}</section> }
function About() { return <section id="about" className="about-3d"><img className="decor moon" src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/moon_icon.11395d36.png" alt="" /><img className="decor lego" src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/lego_icon-1.703bb594.png" alt="" /><div className="about-center"><FadeIn><h2 className="hero-heading">About me</h2></FadeIn><FadeIn delay={.15}><p>With more than five years of experience in design, I focus on branding, web design, and user experience. I truly enjoy working with businesses that aim to stand out and present their best image. Let&apos;s build something incredible together!</p></FadeIn><FadeIn delay={.3}><ContactButton /></FadeIn></div></section> }
function Services() { const items = [['3D Modeling', 'Creation of detailed objects, characters, or environments tailored to specific client needs, ideal for games, products, and visualizations.'], ['Rendering', 'High-quality, photorealistic renders that showcase designs with custom lighting, textures, and materials to bring concepts to life.'], ['Motion Design', 'Dynamic animations and motion graphics that add energy and storytelling to brands, products, and digital experiences.'], ['Branding', 'Crafting cohesive visual identities — from logos to full brand systems — that communicate a clear and memorable presence.'], ['Web Design', 'Designing clean, modern, and conversion-focused websites with attention to layout, typography, and user experience.']]; return <section id="services" className="services-3d"><h2>Services</h2><div className="service-list-3d">{items.map(([name, detail], i) => <FadeIn key={name} delay={i * .08}><article><strong>0{i + 1}</strong><div><h3>{name}</h3><p>{detail}</p></div></article></FadeIn>)}</div></section> }
function ProjectCard({ project, index }: { project: typeof projects[number]; index: number }) { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'start start'] }); const scale = useTransform(scrollYProgress, [0, 1], [1, 1 - (projects.length - 1 - index) * .03]); return <div className="project-wrap" ref={ref}><motion.article className="project-card-3d" style={{ scale, top: index * 28 }}><div className="project-top"><strong>{project[0]}</strong><div><span>{project[1]}</span><h3>{project[2]}</h3></div><a href="#contact">Live Project <ArrowUpRight aria-hidden="true" /></a></div><div className="project-images"><div><img src={project[3][0]} alt={`${project[2]} detail one`} /><img src={project[3][1]} alt={`${project[2]} detail two`} /></div><img src={project[3][2]} alt={`${project[2]} hero`} /></div></motion.article></div> }
function Projects() { return <section id="projects" className="projects-3d"><h2 className="hero-heading">Project</h2>{projects.map((p, i) => <ProjectCard key={p[0]} project={p} index={i} />)}</section> }
export default function Page() { return <main className="portfolio-3d"><section className="hero-3d"><nav><a href="#about">About</a><a href="#services">Price</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav><div className="hero-title"><h1 className="hero-heading">Hi, I&apos;m Jack</h1></div><div className="hero-bottom"><p>A 3D creator driven by crafting striking and unforgettable projects</p><ContactButton /></div><div className="portrait"><img src="https://shrug-person-78902957.figma.site/_components/v2/d24c01ad3a56fc65e942a1f501eb73db42d7cf9a/Rectangle_40443.81459862.png" alt="3D creator portrait" /></div></section><Marquee /><About /><Services /><Projects /><section id="contact" className="contact-3d"><h2 className="hero-heading">Let&apos;s create.</h2><ContactButton /></section></main> }
