'use client'

import { ArrowUpRight, GitBranch, Link, Mail } from 'lucide-react'
import { motion, useScroll, useTransform } from 'framer-motion'
import { useRef } from 'react'
import { portfolio } from '@/data/portfolio'

const projectVisuals = [
  ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85'],
  ['https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=85'],
  ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=85'],
  ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85'],
]

function ContactButton() { return <a className="contact-pill" href="#contact">Let&apos;s work together <ArrowUpRight aria-hidden="true" /></a> }
function FadeIn({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-60px' }} transition={{ duration: .7, delay, ease: [.25, .1, .25, 1] }}>{children}</motion.div> }

function Hero() { return <section className="hero-3d"><nav><a href="#about">About</a><a href="#services">Services</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav><div className="hero-title"><h1 className="hero-heading">Hi, I&apos;m Ansh</h1></div><div className="hero-bottom"><p>{portfolio.intro}</p><ContactButton /></div><div className="portrait"><div className="portrait-initials">AV</div></div></section> }
function Marquee() { const labels = [...portfolio.marquee, ...portfolio.marquee]; return <section className="marquee-3d text-marquee"><div className="marquee-track">{labels.map((label, i) => <span key={`${label}-${i}`}>{label} <b>✦</b></span>)}</div><div className="marquee-track reverse">{labels.slice().reverse().map((label, i) => <span key={`${label}-reverse-${i}`}>{label} <b>✦</b></span>)}</div></section> }
function About() { return <section id="about" className="about-3d"><div className="about-center"><FadeIn><p className="eyebrow">01 / A little context</p><h2 className="hero-heading">Useful software, thoughtfully shipped.</h2></FadeIn><FadeIn delay={.15}><p>I&apos;m Ansh Vishwakarma, a full-stack developer and founder based in Kanpur, India. I combine product thinking, responsive interfaces, APIs, data, and deployment to turn rough ideas into dependable web experiences.</p></FadeIn><FadeIn delay={.3}><ContactButton /></FadeIn></div></section> }
function Services() { return <section id="services" className="services-3d"><h2>What I do</h2><div className="service-list-3d">{portfolio.services.map((item, i) => <FadeIn key={item.title} delay={i * .06}><article><strong>0{i + 1}</strong><div><h3>{item.title}</h3><p>{item.detail}</p></div></article></FadeIn>)}</div></section> }
function ProjectCard({ project, index }: { project: typeof portfolio.projects[number]; index: number }) { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'start start'] }); const scale = useTransform(scrollYProgress, [0, 1], [1, 1 - (portfolio.projects.length - 1 - index) * .03]); const images = projectVisuals[index]; return <div className="project-wrap" ref={ref}><motion.article className="project-card-3d" style={{ scale, top: index * 28 }}><div className="project-top"><strong>{project.number}</strong><div><span>{project.tag}</span><h3>{project.title}</h3><p className="project-description">{project.description}</p></div><a href={project.links[0].href} target="_blank" rel="noreferrer">View project <ArrowUpRight aria-hidden="true" /></a></div><div className="project-images"><div><img src={images[0]} alt="Project interface detail" /><img src={images[1]} alt="Project interface detail" /></div><div className="project-visual-label">{project.title}<small>Designed &amp; built by Ansh</small></div></div></motion.article></div> }
function Projects() { return <section id="projects" className="projects-3d"><p className="eyebrow">02 / Selected work</p><h2 className="hero-heading">Projects</h2>{portfolio.projects.map((project, i) => <ProjectCard key={project.number} project={project} index={i} />)}</section> }
function Contact() { return <section id="contact" className="contact-3d"><p className="eyebrow">03 / Have a project in mind?</p><h2 className="hero-heading">Let&apos;s create.</h2><ContactButton /><div className="socials"><a href={portfolio.links.github} target="_blank" rel="noreferrer" aria-label="GitHub"><GitBranch /></a><a href={portfolio.links.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Link /></a><a href={portfolio.email} aria-label="Email"><Mail /></a></div></section> }
export default function Page() { return <main className="portfolio-3d"><Hero /><Marquee /><About /><Services /><Projects /><Contact /></main> }
